### ISSUE TITLE
Buttons to manipulate all graphs

### ISSUE THREAD

**Issue by nils-ohlmeier** [fippo/webrtc-dump-importer#11]
If I'm looking for how much packet loss occurred on a call I have to individually turn off all the things which influence the scale so that I can't see the little things like NACK, packet loss etc.

It would be nice to have an option somewhere at the top to turn off all graphs and then only turn back on for example NackCount in all graphs.

**Comment by fippo** [comment]
https://stackoverflow.com/questions/16625423/how-can-i-hide-all-the-series-in-highcharts-at-a-time
for a disable-all would help already. And then probably per-type defaults...

**Comment by fippo** [comment]
no buttons yet but now you can filter whole stats types with a selector:
```
document.querySelectorAll('.webrtc-remote-candidate').forEach(e => e.style.display = 'none')
```
also the graph title now contains the webrtc stats type as type=...

needs to be hooked up to checkboxes

**Comment by fippo** [comment]
now with checkboxes :-)

**Comment by fippo** [comment]
http://fippo.github.io/webrtc-dump-importer/bitrate
-- now also with a separate page for just looking at bitrates in a single graph
