### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by rswift** [fippo/webrtc-dump-importer#16]
There is a line of code `var client = JSON.parse(lines.shift());` that is generating errors:

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FileReader.<anonymous> (bitrate.html:44)
```

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FileReader.<anonymous> (rtcstats.html:97)
```

I just ran the tests from https://test.webrtc.org/ to generate the dump, using Chrome 80.0.3987.149 (Official Build) (64-bit). Breakpointing and inspecting the `lines` array, it looks fine (as in, there are the same number of array entries as lines of text in the source file), but I'm not familiar enough with JavaScript to know why the JSON parser might fail like this. I tried manually adding blank lines to the end of the file in case there was a weirdy with the last line - same result.

I checked the file for JSON validity using jsonlint.com and it validated fine.

I tried it in Safari 13.0.5 (15608.5.11) and get a different error from the same line(s) of code:
```
SyntaxError: JSON Parse error: Expected '}'
parse — bitrate.html:44
(anonymous function) — bitrate.html:44
```

Firefox 71.0 (64-bit):
```
SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data
```

All this on macOS 10.15.3.

Thanks in advance for any assistance or thoughts.

Cheers - Robert...

**Comment by rswift** [comment]
I'm definitely feeling around in the dark, but it looks like `something = JSON.parse(e.target.result)` successfully load parses into an object, so the `indexOf('\n')` seems like it may be the cause of the problem? However, I notice that the UserAgent (the code looks for `userAgent`) has changed and having the pages like rtcstats.html load the content by forcing the check, essentially blank data is loaded?

**Comment by nemani** [comment]
For me the file is successfully imported in `index.html` but not for the other pages.

**Comment by fippo** [comment]
index.html is using the webrtc-internals format. The other pages are using the rtcstats dump format.

**Comment by rswift** [comment]
A comment in the HTML (like index.html has), would be quite handy to help a stupid person such as myself... 😏 
Thanks for the clarification though @fippo
