### ISSUE TITLE
Remove legacy stats code

### ISSUE THREAD

**Issue by fippo** [fippo/webrtc-dump-importer#20]
Now that Chrome can no longer generate legacy stats reports as of M122
  https://bugs.chromium.org/p/chromium/issues/detail?id=822696#c37
we can remove support here as well. Ideally with some detection similar to what is done for `createLegacyCandidateTable` which can suggest "checkout an old version of this repo"

Delete! Delete!

**Comment by henbos** [comment]
Delete! Delete!

**Comment by fippo** [comment]
Done with a note pointing to the last commit
